apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bread-sheet-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fabelhaft-io/bread-sheet.git'
    targetRevision: HEAD
    path: terraform/k8s # The directory ArgoCD should watch
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
